### ISSUE TITLE
Update repo and next.js suggestion

### ISSUE THREAD

**Issue by MauriceMahan** [alex996/graphql-chat#5]
Hi Alex,

Thank you for creating the MERN stack video series. Can you update this repo with the latest code from the videos? Latest commit is from around the directives video I believe.

Also have you decided on what you will be using for creating the frontend of the site? I wanted to suggest [next.js](https://github.com/zeit/next.js) since it's React but also server-side rendered. It can also be integrated with the Express and Apollo setup you've already implemented.

**Comment by alex996** [comment]
I will update the repo soon. Thanks for the suggestions!

**Comment by alex996** [comment]
The code has been updated! I have a few interesting ideas for the front-end app, and MUI v4 is about to go stable just in time, so it'd be perfect timing to give a refresher to the MUI series as well. I'll keep SSR and Next in the back of my mind.
