### ISSUE TITLE
Error with User resolver validate

### ISSUE THREAD

**Issue by northersky** [alex996/graphql-chat#7]
Hi,

resolvers\chat.js

The validate method expect two parameters:

`await Joi.validate(args, startChat(userIds), { abortEarly: false })`

With correction
`await Joi.validate(args, startChat(args), { abortEarly: false })`

**Comment by alex996** [comment]
`startChat(userId)` is a bit unique in that it takes the ID of the user that should be absent from `userIds` array. In other words, it's the signed-in user's ID. It gets pushed to the array later on

```js
userIds.push(userId)
```

I exclude it on purpose to make validation easier. Hope this clarifies it.
